apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:    # These are additional options that specify high-level 
                  # configuration around the object.